In [2]:
import pandas as pd

games = pd.read_csv("../data/raw/games.csv")

games.head()

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
0,2025-02-12,22400769,Final,1610612738,1610612759,2024,1610612738,116.0,0.462,0.667,...,25.0,56.0,1610612759,103.0,0.438,0.833,0.231,30.0,38.0,1
1,2025-02-12,22400770,Final,1610612753,1610612766,2024,1610612753,102.0,0.411,0.737,...,22.0,52.0,1610612766,86.0,0.395,0.933,0.308,21.0,43.0,1
2,2025-02-12,22400771,Final,1610612764,1610612754,2024,1610612764,130.0,0.485,0.813,...,29.0,46.0,1610612754,134.0,0.467,0.900,0.457,38.0,42.0,0
3,2025-02-12,22400772,Final,1610612751,1610612755,2024,1610612751,100.0,0.471,0.800,...,23.0,50.0,1610612755,96.0,0.432,0.818,0.242,25.0,38.0,1
4,2025-02-12,22400773,Final,1610612752,1610612737,2024,1610612752,149.0,0.574,0.811,...,28.0,39.0,1610612737,148.0,0.500,0.686,0.368,43.0,47.0,1

In [3]:
#investigating and removing duplicates

In [4]:
duplicate_games = games[games["GAME_ID"].duplicated(keep=False)]

duplicate_games.sort_values("GAME_ID").head(20)

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
5639,2020-12-25,22000006,Final,1610612749,1610612744,2020,1610612749,138.0,0.556,0.692,...,25.0,60.0,1610612744,99.0,0.343,0.840,0.222,14.0,43.0,1
6229,2020-12-25,22000006,Final,1610612749,1610612744,2020,1610612749,138.0,0.556,0.692,...,25.0,60.0,1610612744,99.0,0.343,0.840,0.222,14.0,43.0,1
6230,2020-12-25,22000007,Final,1610612738,1610612751,2020,1610612738,95.0,0.378,0.684,...,23.0,47.0,1610612751,123.0,0.539,0.839,0.517,21.0,43.0,0
5640,2020-12-25,22000007,Final,1610612738,1610612751,2020,1610612738,95.0,0.378,0.684,...,23.0,47.0,1610612751,123.0,0.539,0.839,0.517,21.0,43.0,0
5644,2020-12-23,22000011,Final,1610612754,1610612752,2020,1610612754,121.0,0.489,0.724,...,28.0,50.0,1610612752,107.0,0.459,0.739,0.429,25.0,40.0,1
6231,2020-12-23,22000011,Final,1610612754,1610612752,2020,1610612754,121.0,0.489,0.724,...,28.0,50.0,1610612752,107.0,0.459,0.739,0.429,25.0,40.0,1
6232,2020-12-23,22000013,Final,1610612755,1610612764,2020,1610612755,113.0,0.471,0.767,...,22.0,47.0,1610612764,107.0,0.459,0.696,0.481,28.0,40.0,1
5646,2020-12-23,22000013,Final,1610612755,1610612764,2020,1610612755,113.0,0.471,0.767,...,22.0,47.0,1610612764,107.0,0.459,0.696,0.481,28.0,40.0,1
5649,2020-12-23,22000015,Final,1610612741,1610612737,2020,1610612741,104.0,0.414,0.857,...,20.0,37.0,1610612737,124.0,0.538,0.828,0.400,24.0,46.0,0
6233,2020-12-23,22000015,Final,1610612741,1610612737,2020,1610612741,104.0,0.414,0.857,...,20.0,37.0,1610612737,124.0,0.538,0.828,0.400,24.0,46.0,0
6234,2020-12-23,22000018,Final,1610612750,1610612765,2020,1610612750,111.0,0.432,0.857,...,25.0,48.0,1610612765,101.0,0.484,0.375,0.229,29.0,44.0,1
5651,2020-12-23,22000018,Final,1610612750,1610612765,2020,1610612750,111.0,0.432,0.857,...,25.0,48.0,1610612765,101.0,0.484,0.375,0.229,29.0,44.0,1
5628,2020-12-26,22000021,Final,1610612763,1610612737,2020,1610612763,112.0,0.398,0.862,...,20.0,46.0,1610612737,122.0,0.427,0.868,0.361,23.0,54.0,0
6224,2020-12-26,22000021,Final,1610612763,1610612737,2020,1610612763,112.0,0.398,0.862,...,20.0,46.0,1610612737,122.0,0.427,0.868,0.361,23.0,54.0,0
6225,2020-12-26,22000022,Final,1610612766,1610612760,2020,1610612766,107.0,0.398,0.625,...,27.0,47.0,1610612760,109.0,0.455,0.792,0.278,25.0,54.0,0
5629,2020-12-26,22000022,Final,1610612766,1610612760,2020,1610612766,107.0,0.398,0.625,...,27.0,47.0,1610612760,109.0,0.455,0.792,0.278,25.0,54.0,0
5634,2020-12-26,22000027,Final,1610612759,1610612761,2020,1610612759,119.0,0.470,0.688,...,36.0,53.0,1610612761,114.0,0.458,0.733,0.366,32.0,46.0,1
6226,2020-12-26,22000027,Final,1610612759,1610612761,2020,1610612759,119.0,0.470,0.688,...,36.0,53.0,1610612761,114.0,0.458,0.733,0.366,32.0,46.0,1
6227,2020-12-26,22000028,Final,1610612762,1610612750,2020,1610612762,111.0,0.383,0.784,...,15.0,57.0,1610612750,116.0,0.446,0.722,0.448,21.0,40.0,0
5635,2020-12-26,22000028,Final,1610612762,1610612750,2020,1610612762,111.0,0.383,0.784,...,15.0,57.0,1610612750,116.0,0.446,0.722,0.448,21.0,40.0,0

In [5]:
duplicate_games["GAME_ID"].value_counts().head(10)

GAME_ID
22000070    2
22000072    2
22000076    2
22000077    2
22000065    2
22000067    2
22000057    2
22000046    2
22000049    2
22000051    2
Name: count, dtype: int64

In [6]:
duplicate_games.groupby("GAME_ID").size().value_counts()

2    29
Name: count, dtype: int64

In [7]:
duplicate_games.groupby("GAME_ID")["PTS_home"].nunique().value_counts()

PTS_home
1    29
Name: count, dtype: int64

In [8]:
duplicate_games.groupby("GAME_ID")["PTS_away"].nunique().value_counts()

PTS_away
1    29
Name: count, dtype: int64

In [9]:
games["GAME_DATE_EST"] = pd.to_datetime(games["GAME_DATE_EST"])

In [10]:
games["GAME_DATE_EST"].dtype

dtype('<M8[us]')

In [11]:
games = games.sort_values("GAME_DATE_EST").reset_index(drop=True)

In [12]:
games[["GAME_DATE_EST", "GAME_ID", "SEASON"]].head(10)

  GAME_DATE_EST   GAME_ID  SEASON
0    2003-10-05  10300001    2003
1    2003-10-06  10300002    2003
2    2003-10-07  10300009    2003
3    2003-10-07  10300005    2003
4    2003-10-07  10300007    2003
5    2003-10-07  10300008    2003
6    2003-10-07  10300004    2003
7    2003-10-07  10300003    2003
8    2003-10-07  10300010    2003
9    2003-10-07  10300006    2003

In [13]:
games["TOTAL_POINTS"] = games["PTS_home"] + games["PTS_away"]

In [14]:
games[[
    "GAME_DATE_EST",
    "TEAM_ID_home",
    "PTS_home",
    "TEAM_ID_away",
    "PTS_away",
    "TOTAL_POINTS"
]].head(10)

  GAME_DATE_EST  TEAM_ID_home  PTS_home  TEAM_ID_away  PTS_away  TOTAL_POINTS
0    2003-10-05    1610612762      90.0    1610612742      85.0         175.0
1    2003-10-06    1610612763     105.0    1610612749      94.0         199.0
2    2003-10-07    1610612758     101.0    1610612746      82.0         183.0
3    2003-10-07    1610612757     104.0    1610612745      80.0         184.0
4    2003-10-07    1610612748      86.0    1610612755      79.0         165.0
5    2003-10-07    1610612756      79.0    1610612751     101.0         180.0
6    2003-10-07    1610612742      99.0    1610612753      89.0         188.0
7    2003-10-07    1610612765      96.0    1610612739     100.0         196.0
8    2003-10-07    1610612764     104.0    1610612752      86.0         190.0
9    2003-10-07    1610612747       NaN    1610612744       NaN           NaN

In [15]:
games["TOTAL_POINTS"].describe()

count    29656.000000
mean       206.562753
std         23.882753
min         69.000000
25%        190.000000
50%        206.000000
75%        223.000000
max        351.000000
Name: TOTAL_POINTS, dtype: float64

In [16]:
duplicate_games.sort_values("GAME_ID").head(20)

,GAME_DATE_EST,GAME_ID,GAME_STATUS_TEXT,HOME_TEAM_ID,VISITOR_TEAM_ID,SEASON,TEAM_ID_home,PTS_home,FG_PCT_home,FT_PCT_home,...,AST_home,REB_home,TEAM_ID_away,PTS_away,FG_PCT_away,FT_PCT_away,FG3_PCT_away,AST_away,REB_away,HOME_TEAM_WINS
5639,2020-12-25,22000006,Final,1610612749,1610612744,2020,1610612749,138.0,0.556,0.692,...,25.0,60.0,1610612744,99.0,0.343,0.840,0.222,14.0,43.0,1
6229,2020-12-25,22000006,Final,1610612749,1610612744,2020,1610612749,138.0,0.556,0.692,...,25.0,60.0,1610612744,99.0,0.343,0.840,0.222,14.0,43.0,1
6230,2020-12-25,22000007,Final,1610612738,1610612751,2020,1610612738,95.0,0.378,0.684,...,23.0,47.0,1610612751,123.0,0.539,0.839,0.517,21.0,43.0,0
5640,2020-12-25,22000007,Final,1610612738,1610612751,2020,1610612738,95.0,0.378,0.684,...,23.0,47.0,1610612751,123.0,0.539,0.839,0.517,21.0,43.0,0
5644,2020-12-23,22000011,Final,1610612754,1610612752,2020,1610612754,121.0,0.489,0.724,...,28.0,50.0,1610612752,107.0,0.459,0.739,0.429,25.0,40.0,1
6231,2020-12-23,22000011,Final,1610612754,1610612752,2020,1610612754,121.0,0.489,0.724,...,28.0,50.0,1610612752,107.0,0.459,0.739,0.429,25.0,40.0,1
6232,2020-12-23,22000013,Final,1610612755,1610612764,2020,1610612755,113.0,0.471,0.767,...,22.0,47.0,1610612764,107.0,0.459,0.696,0.481,28.0,40.0,1
5646,2020-12-23,22000013,Final,1610612755,1610612764,2020,1610612755,113.0,0.471,0.767,...,22.0,47.0,1610612764,107.0,0.459,0.696,0.481,28.0,40.0,1
5649,2020-12-23,22000015,Final,1610612741,1610612737,2020,1610612741,104.0,0.414,0.857,...,20.0,37.0,1610612737,124.0,0.538,0.828,0.400,24.0,46.0,0
6233,2020-12-23,22000015,Final,1610612741,1610612737,2020,1610612741,104.0,0.414,0.857,...,20.0,37.0,1610612737,124.0,0.538,0.828,0.400,24.0,46.0,0
6234,2020-12-23,22000018,Final,1610612750,1610612765,2020,1610612750,111.0,0.432,0.857,...,25.0,48.0,1610612765,101.0,0.484,0.375,0.229,29.0,44.0,1
5651,2020-12-23,22000018,Final,1610612750,1610612765,2020,1610612750,111.0,0.432,0.857,...,25.0,48.0,1610612765,101.0,0.484,0.375,0.229,29.0,44.0,1
5628,2020-12-26,22000021,Final,1610612763,1610612737,2020,1610612763,112.0,0.398,0.862,...,20.0,46.0,1610612737,122.0,0.427,0.868,0.361,23.0,54.0,0
6224,2020-12-26,22000021,Final,1610612763,1610612737,2020,1610612763,112.0,0.398,0.862,...,20.0,46.0,1610612737,122.0,0.427,0.868,0.361,23.0,54.0,0
6225,2020-12-26,22000022,Final,1610612766,1610612760,2020,1610612766,107.0,0.398,0.625,...,27.0,47.0,1610612760,109.0,0.455,0.792,0.278,25.0,54.0,0
5629,2020-12-26,22000022,Final,1610612766,1610612760,2020,1610612766,107.0,0.398,0.625,...,27.0,47.0,1610612760,109.0,0.455,0.792,0.278,25.0,54.0,0
5634,2020-12-26,22000027,Final,1610612759,1610612761,2020,1610612759,119.0,0.470,0.688,...,36.0,53.0,1610612761,114.0,0.458,0.733,0.366,32.0,46.0,1
6226,2020-12-26,22000027,Final,1610612759,1610612761,2020,1610612759,119.0,0.470,0.688,...,36.0,53.0,1610612761,114.0,0.458,0.733,0.366,32.0,46.0,1
6227,2020-12-26,22000028,Final,1610612762,1610612750,2020,1610612762,111.0,0.383,0.784,...,15.0,57.0,1610612750,116.0,0.446,0.722,0.448,21.0,40.0,0
5635,2020-12-26,22000028,Final,1610612762,1610612750,2020,1610612762,111.0,0.383,0.784,...,15.0,57.0,1610612750,116.0,0.446,0.722,0.448,21.0,40.0,0

In [17]:
duplicate_games["GAME_ID"].value_counts().head(10)

GAME_ID
22000070    2
22000072    2
22000076    2
22000077    2
22000065    2
22000067    2
22000057    2
22000046    2
22000049    2
22000051    2
Name: count, dtype: int64

In [18]:
games = games.drop_duplicates(subset="GAME_ID", keep="first")

In [19]:
games["GAME_ID"].duplicated().sum()

np.int64(0)

In [20]:
#invstigating missing and removing them

In [21]:
games = games.dropna(subset=[
    "PTS_home",
    "PTS_away",
    "FG_PCT_home",
    "FG_PCT_away",
    "FT_PCT_home",
    "FT_PCT_away",
    "FG3_PCT_home",
    "FG3_PCT_away",
    "AST_home",
    "AST_away",
    "REB_home",
    "REB_away"
])

In [22]:
games.isnull().sum().sum()

np.int64(0)

In [23]:
#conversion of data

In [24]:
games["GAME_DATE_EST"] = pd.to_datetime(games["GAME_DATE_EST"])

In [25]:
games["GAME_DATE_EST"].dtype

dtype('<M8[us]')

In [26]:
#sorting games chronologically

In [27]:
games = games.sort_values("GAME_DATE_EST").reset_index(drop=True)

In [28]:
games[[
    "GAME_DATE_EST",
    "GAME_ID",
    "TEAM_ID_home",
    "TEAM_ID_away"
]].head()

  GAME_DATE_EST   GAME_ID  TEAM_ID_home  TEAM_ID_away
0    2003-10-05  10300001    1610612762    1610612742
1    2003-10-06  10300002    1610612763    1610612749
2    2003-10-07  10300009    1610612758    1610612746
3    2003-10-07  10300005    1610612757    1610612745
4    2003-10-07  10300007    1610612748    1610612755

In [29]:
games[[
    "GAME_DATE_EST",
    "GAME_ID",
    "TEAM_ID_home",
    "TEAM_ID_away"
]].tail()

      GAME_DATE_EST   GAME_ID  TEAM_ID_home  TEAM_ID_away
29622    2025-02-12  22400782    1610612742    1610612744
29623    2025-02-12  22400783    1610612746    1610612763
29624    2025-02-12  22400771    1610612764    1610612754
29625    2025-02-12  22400778    1610612760    1610612748
29626    2025-02-12  22400769    1610612738    1610612759

In [30]:
#create target variable for over/under

In [31]:
games["TOTAL_POINTS"] = games["PTS_home"] + games["PTS_away"]

In [32]:
games[[
    "GAME_DATE_EST",
    "TEAM_ID_home",
    "PTS_home",
    "TEAM_ID_away",
    "PTS_away",
    "TOTAL_POINTS"
]].head(10)

  GAME_DATE_EST  TEAM_ID_home  PTS_home  TEAM_ID_away  PTS_away  TOTAL_POINTS
0    2003-10-05    1610612762      90.0    1610612742      85.0         175.0
1    2003-10-06    1610612763     105.0    1610612749      94.0         199.0
2    2003-10-07    1610612758     101.0    1610612746      82.0         183.0
3    2003-10-07    1610612757     104.0    1610612745      80.0         184.0
4    2003-10-07    1610612748      86.0    1610612755      79.0         165.0
5    2003-10-07    1610612756      79.0    1610612751     101.0         180.0
6    2003-10-07    1610612742      99.0    1610612753      89.0         188.0
7    2003-10-07    1610612765      96.0    1610612739     100.0         196.0
8    2003-10-07    1610612764     104.0    1610612752      86.0         190.0
9    2003-10-08    1610612754      62.0    1610612741      58.0         120.0

In [33]:
games["TOTAL_POINTS"].describe()

count    29627.000000
mean       206.549431
std         23.880709
min         69.000000
25%        190.000000
50%        206.000000
75%        223.000000
max        351.000000
Name: TOTAL_POINTS, dtype: float64

In [34]:
games.to_csv("../data/processed/games_cleaned.csv", index=False)

In [35]:
import os

os.path.exists("../data/processed/games_cleaned.csv")

True

In [36]:
games.shape

(29627, 22)